In [2]:
import numpy as np

In [5]:
l = list(range(0,21,2))
l

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [6]:
my_array = np.array(range(0,21,2))

In [7]:
my_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
for i in my_array:
    print(i)

0
2
4
6
8
10
12
14
16
18
20


In [14]:
l = [1, 'is', 'fun']

In [17]:
type(l[0])

int

In [18]:
for i in l:
    print(type(i))

<class 'int'>
<class 'str'>
<class 'str'>


In [19]:
my_array_2 = np.array(l)

In [22]:
my_array_2

array(['1', 'is', 'fun'], dtype='<U11')

In [23]:
for i in my_array_2:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [24]:
my_array * 2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [25]:
my_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [27]:
l*2

[1, 'is', 'fun', 1, 'is', 'fun']

In [28]:

l1 = []
l = list(my_array)
for i in l:
    l1.append(i*2)

l1

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40]

In [29]:
l1 + 2

TypeError: can only concatenate list (not "int") to list

In [32]:
my_array + 0.5

array([ 0.5,  2.5,  4.5,  6.5,  8.5, 10.5, 12.5, 14.5, 16.5, 18.5, 20.5])

In [34]:
2**(my_array + 0.5)

array([1.41421356e+00, 5.65685425e+00, 2.26274170e+01, 9.05096680e+01,
       3.62038672e+02, 1.44815469e+03, 5.79261875e+03, 2.31704750e+04,
       9.26819000e+04, 3.70727600e+05, 1.48291040e+06])

+-/*, % // ** Type of operators

np.sqrt

In [36]:
np.sqrt(my_array)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595])

In [37]:
np.exp(my_array)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07, 4.85165195e+08])

In [38]:
np.log(my_array)

C:\Users\Mehak Chawla\AppData\Local\Temp\ipykernel_19320\3536048703.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(my_array)


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227])

In [ ]:
np.array([0,2])

False

In [46]:
my_array.tolist()

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [47]:
my_array.size

11

In [48]:
len(my_array)

11

In [49]:
np.sum(my_array)

110

In [50]:
np.abs(my_array)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [51]:
np.sum(my_array)

110

In [52]:
np.size(my_array)

11

In [53]:
len(my_array)

11

In [55]:
np.ceil(my_array)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [57]:
np.around(my_array,decimals = -6)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
a1 = np.array(range(0,21,2))

In [59]:
a = np.arange(0,21,2)

In [65]:
list(str(a))

['[',
 ' ',
 '0',
 ' ',
 ' ',
 '2',
 ' ',
 ' ',
 '4',
 ' ',
 ' ',
 '6',
 ' ',
 ' ',
 '8',
 ' ',
 '1',
 '0',
 ' ',
 '1',
 '2',
 ' ',
 '1',
 '4',
 ' ',
 '1',
 '6',
 ' ',
 '1',
 '8',
 ' ',
 '2',
 '0',
 ']']

In [66]:
a[0]

0

In [67]:
a[2]

4

In [68]:
list(enumerate(a))

[(0, 0),
 (1, 2),
 (2, 4),
 (3, 6),
 (4, 8),
 (5, 10),
 (6, 12),
 (7, 14),
 (8, 16),
 (9, 18),
 (10, 20)]

In [69]:
enumerate(a)

In [70]:
tuple(enumerate(a))

((0, 0),
 (1, 2),
 (2, 4),
 (3, 6),
 (4, 8),
 (5, 10),
 (6, 12),
 (7, 14),
 (8, 16),
 (9, 18),
 (10, 20))

In [75]:
a[2:1]

array([], dtype=int32)

In [72]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
a[::-1]

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [90]:
b = [1,2,3]


In [91]:
list(reversed(b))

[3, 2, 1]

In [100]:
b = [1,2,3,4,5]

In [101]:
b1= []
for i in b:
    b1.insert(0,i)

In [102]:
b1

[5, 4, 3, 2, 1]

In [104]:
a = np.array(range(0,10,2))

In [105]:
a

array([0, 2, 4, 6, 8])

In [106]:
b = a

In [107]:
b

array([0, 2, 4, 6, 8])

In [108]:
b[0:2] = 1000

In [111]:
b= a.copy()

In [112]:
b

array([1000, 1000,    4,    6,    8])

In [113]:
b[1:3] = 1000000

In [114]:
b

array([   1000, 1000000, 1000000,       6,       8])

In [115]:
a

array([1000, 1000,    4,    6,    8])

In [117]:
a = np.array([1,2,3,4])

In [118]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [120]:
a.shape

(4,)

In [123]:
a = np.arange(0,100).reshape(10,10)

In [124]:
a.shape

(10, 10)

In [125]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [128]:
a.sum(axis = 1)

array([ 45, 145, 245, 345, 445, 545, 645, 745, 845, 945])

In [129]:
a.prod(axis = 0)

array([          0, -1120375461,   189267968,  1769966759,  1437597696,
       -1881096997,  -912261120,  -204841865,  1467482112, -1421546757])

In [133]:
a.cumprod(axis = 3)

AxisError: axis 3 is out of bounds for array of dimension 2

In [134]:
a.prodsum()

AttributeError: 'numpy.ndarray' object has no attribute 'prodsum'

In [136]:
a = np.array(range(0,21,1))

In [145]:
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [138]:
mask1 = a%2 ==0

In [139]:
mask1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [147]:
a[(a>5) | (a%2 ==0) ]

array([ 0,  2,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [148]:
Random Numbers 

SyntaxError: invalid syntax (1769828557.py, line 1)

In [149]:
import random

In [159]:
random.seed(123)
a = random.randint(0,100)

In [160]:
a

6

In [157]:
a = random.randint(0,100)

In [163]:
c = np.random.normal(5,2,100)

In [166]:
b1 = np.random.choice(c,5,replace = True)

In [165]:
b1

array([5.36009295, 3.89505253, 2.96905091, 2.6638461 , 5.04787688])

In [167]:
Pandas from zero to hero

SyntaxError: invalid syntax (745865617.py, line 1)

In [168]:
import pandas as pd

In [169]:
titanic = pd.read_csv('titanic.csv')

In [170]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
0,0,3,male,22.0,1,0,7.2500,S,NaN
1,1,1,female,38.0,1,0,71.2833,C,C
2,1,3,female,26.0,0,0,7.9250,S,NaN
3,1,1,female,35.0,1,0,53.1000,S,C
4,0,3,male,35.0,0,0,8.0500,S,NaN
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,NaN
887,1,1,female,19.0,0,0,30.0000,S,B
888,0,3,female,NaN,1,2,23.4500,S,NaN
889,1,1,male,26.0,0,0,30.0000,C,C


In [171]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
0,0,3,male,22.0,1,0,7.2500,S,NaN
1,1,1,female,38.0,1,0,71.2833,C,C
2,1,3,female,26.0,0,0,7.9250,S,NaN
3,1,1,female,35.0,1,0,53.1000,S,C
4,0,3,male,35.0,0,0,8.0500,S,NaN


In [172]:
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
886,0,2,male,27.0,0,0,13.00,S,NaN
887,1,1,female,19.0,0,0,30.00,S,B
888,0,3,female,NaN,1,2,23.45,S,NaN
889,1,1,male,26.0,0,0,30.00,C,C
890,0,3,male,32.0,0,0,7.75,Q,NaN


In [174]:
titanic.tail(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
881,0,3,male,33.0,0,0,7.8958,S,NaN
882,0,3,female,22.0,0,0,10.5167,S,NaN
883,0,2,male,28.0,0,0,10.5000,S,NaN
884,0,3,male,25.0,0,0,7.0500,S,NaN
885,0,3,female,39.0,0,5,29.1250,Q,NaN
886,0,2,male,27.0,0,0,13.0000,S,NaN
887,1,1,female,19.0,0,0,30.0000,S,B
888,0,3,female,NaN,1,2,23.4500,S,NaN
889,1,1,male,26.0,0,0,30.0000,C,C
890,0,3,male,32.0,0,0,7.7500,Q,NaN


In [175]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck'],
      dtype='object')

In [180]:
titanic.describe(include = 'O')

,sex,embarked,deck
count,891,889,203
unique,2,3,7
top,male,S,C
freq,577,644,59


In [181]:
len(titanic)

891

In [182]:
titanic.shape

(891, 9)

In [184]:
max(titanic)

'survived'

In [187]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [188]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   deck      203 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB


In [189]:
titanic.min(numeric_only = True)

survived    0.00
pclass      1.00
age         0.42
sibsp       0.00
parch       0.00
fare        0.00
dtype: float64

In [193]:
titanic.max(numeric_only= True)

survived      1.0000
pclass        3.0000
age          80.0000
sibsp         8.0000
parch         6.0000
fare        512.3292
dtype: float64

In [200]:
titanic.sort_values('age',ascending= False)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
630,1,1,male,80.0,0,0,30.0000,S,A
851,0,3,male,74.0,0,0,7.7750,S,NaN
493,0,1,male,71.0,0,0,49.5042,C,NaN
96,0,1,male,71.0,0,0,34.6542,C,A
116,0,3,male,70.5,0,0,7.7500,Q,NaN
...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,NaN
863,0,3,female,NaN,8,2,69.5500,S,NaN
868,0,3,male,NaN,0,0,9.5000,S,NaN
878,0,3,male,NaN,0,0,7.8958,S,NaN


In [203]:
titanic.age + 100

0      122.0
1      138.0
2      126.0
3      135.0
4      135.0
       ...  
886    127.0
887    119.0
888      NaN
889    126.0
890    132.0
Name: age, Length: 891, dtype: float64

In [223]:
titanic.loc[1:]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
1,1,1,female,38.0,1,0,71.2833,C,C
2,1,3,female,26.0,0,0,7.9250,S,NaN
3,1,1,female,35.0,1,0,53.1000,S,C
4,0,3,male,35.0,0,0,8.0500,S,NaN
5,0,3,male,NaN,0,0,8.4583,Q,NaN
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,NaN
887,1,1,female,19.0,0,0,30.0000,S,B
888,0,3,female,NaN,1,2,23.4500,S,NaN
889,1,1,male,26.0,0,0,30.0000,C,C


In [222]:
titanic.iloc[45:]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,deck
45,0,3,male,NaN,0,0,8.0500,S,NaN
46,0,3,male,NaN,1,0,15.5000,Q,NaN
47,1,3,female,NaN,0,0,7.7500,Q,NaN
48,0,3,male,NaN,2,0,21.6792,C,NaN
49,0,3,female,18.0,1,0,17.8000,S,NaN
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,NaN
887,1,1,female,19.0,0,0,30.0000,S,B
888,0,3,female,NaN,1,2,23.4500,S,NaN
889,1,1,male,26.0,0,0,30.0000,C,C


In [230]:
titanic.set_index('sex',inplace = True)

In [235]:
titanic.loc[['male','female']]

,survived,pclass,age,sibsp,parch,fare,embarked,deck
sex,,,,,,,,
male,0,3,22.0,1,0,7.2500,S,NaN
male,0,3,35.0,0,0,8.0500,S,NaN
male,0,3,NaN,0,0,8.4583,Q,NaN
male,0,1,54.0,0,0,51.8625,S,E
male,0,3,2.0,3,1,21.0750,S,NaN
...,...,...,...,...,...,...,...,...
female,1,2,25.0,0,1,26.0000,S,NaN
female,0,3,22.0,0,0,10.5167,S,NaN
female,0,3,39.0,0,5,29.1250,Q,NaN


In [237]:
titanic.iloc[0:10]

,survived,pclass,age,sibsp,parch,fare,embarked,deck
sex,,,,,,,,
male,0,3,22.0,1,0,7.2500,S,NaN
female,1,1,38.0,1,0,71.2833,C,C
female,1,3,26.0,0,0,7.9250,S,NaN
female,1,1,35.0,1,0,53.1000,S,C
male,0,3,35.0,0,0,8.0500,S,NaN
male,0,3,NaN,0,0,8.4583,Q,NaN
male,0,1,54.0,0,0,51.8625,S,E
male,0,3,2.0,3,1,21.0750,S,NaN
female,1,3,27.0,0,2,11.1333,S,NaN


In [241]:
titanic.iloc[[1,2,3,4]]

,survived,pclass,age,sibsp,parch,fare,embarked,deck
sex,,,,,,,,
female,1,1,38.0,1,0,71.2833,C,C
female,1,3,26.0,0,0,7.9250,S,NaN
female,1,1,35.0,1,0,53.1000,S,C
male,0,3,35.0,0,0,8.0500,S,NaN


In [256]:
summer = pd.read_csv('summer.csv',index_col = 'Athlete')

In [243]:
summer

,Year,City,Sport,Discipline,Athlete,Gender,Event,Medal
Country,,,,,,,,
HUN,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",Men,100M Freestyle,Gold
AUT,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",Men,100M Freestyle,Silver
GRE,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",Men,100M Freestyle For Sailors,Bronze
GRE,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",Men,100M Freestyle For Sailors,Gold
GRE,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...
POL,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",Men,Wg 84 KG,Bronze
IRI,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",Men,Wg 96 KG,Gold
RUS,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",Men,Wg 96 KG,Silver


In [254]:
summer.iloc[:,4].equals(summer['Athlete'])

True

In [257]:
summer.loc["DRIVAS, Dimitrios":"BLAKE, Arthur", "City":"Discipline"]

,City,Sport,Discipline
Athlete,,,
"DRIVAS, Dimitrios",Athens,Aquatics,Swimming
"MALOKINIS, Ioannis",Athens,Aquatics,Swimming
"CHASAPIS, Spiridon",Athens,Aquatics,Swimming
"CHOROPHAS, Efstathios",Athens,Aquatics,Swimming
"HAJOS, Alfred",Athens,Aquatics,Swimming
"ANDREOU, Joannis",Athens,Aquatics,Swimming
"CHOROPHAS, Efstathios",Athens,Aquatics,Swimming
"NEUMANN, Paul",Athens,Aquatics,Swimming
"PEPANOS, Antonios",Athens,Aquatics,Swimming


In [ ]:
summer.reindex(index = ['DRIVAS, Dimitrios','MALOKINIS, Ioannis'], columns = ["City"],)

ValueError: cannot reindex on an axis with duplicate labels

In [265]:
summer = pd.read_csv("summer.csv")

In [266]:
summer.reindex(index = [0, 5, 30000, 40000], columns =  ["Athlete", "Medal", "Age"])

,Athlete,Medal,Age
0,"HAJOS, Alfred",Gold,NaN
5,"CHOROPHAS, Efstathios",Bronze,NaN
30000,"PAUTARAN, Maryna",Bronze,NaN
40000,NaN,NaN,NaN


In [267]:
summer

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze


In [270]:
summer.reindex(index = summer.index[3:66], columns = ['Athlete','Medal'])

,Athlete,Medal
3,"MALOKINIS, Ioannis",Gold
4,"CHASAPIS, Spiridon",Silver
5,"CHOROPHAS, Efstathios",Bronze
6,"HAJOS, Alfred",Gold
7,"ANDREOU, Joannis",Silver
...,...,...
61,"FLAMENG, Léon",Bronze
62,"MASSON, Paul",Gold
63,"NIKOLOPOULOS, Stamatios",Silver
64,"PIERRAKOS-MAVROMICHALIS, Perikles",Bronze


In [273]:
type(titanic.age.dtype)

numpy.dtypes.Float64DType

In [281]:
summer.iloc[0:5],[100,200]

(   Year    City     Sport Discipline             Athlete Country Gender  \
 0  1896  Athens  Aquatics   Swimming       HAJOS, Alfred     HUN    Men   
 1  1896  Athens  Aquatics   Swimming    HERSCHMANN, Otto     AUT    Men   
 2  1896  Athens  Aquatics   Swimming   DRIVAS, Dimitrios     GRE    Men   
 3  1896  Athens  Aquatics   Swimming  MALOKINIS, Ioannis     GRE    Men   
 4  1896  Athens  Aquatics   Swimming  CHASAPIS, Spiridon     GRE    Men   
 
                         Event   Medal  
 0              100M Freestyle    Gold  
 1              100M Freestyle  Silver  
 2  100M Freestyle For Sailors  Bronze  
 3  100M Freestyle For Sailors    Gold  
 4  100M Freestyle For Sailors  Silver  ,
 [100, 200])

In [282]:
rows = list(range(0,5)) + [100,200]

In [283]:
rows

[0, 1, 2, 3, 4, 100, 200]

In [299]:
summer.iloc[rows]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver
100,1896,Athens,Gymnastics,Artistic G.,"FLATOW, Alfred",GER,Men,"Team, Parallel Bars",Gold
200,1900,Paris,Aquatics,Water polo,"KEMP, Peter",GBR,Men,Water Polo,Gold


In [289]:
columns = list(summer.columns)

In [290]:
type(columns)

list

In [293]:
columns.pop(2)

'Sport'

In [294]:
columns

['Year', 'City', 'Discipline', 'Athlete', 'Country', 'Gender', 'Event']

In [313]:
summer.Year[summer.Year == 2012]

29216    2012
29217    2012
29218    2012
29219    2012
29220    2012
         ... 
31160    2012
31161    2012
31162    2012
31163    2012
31164    2012
Name: Year, Length: 1949, dtype: int64

In [302]:
summer.Year.dtype

dtype('int64')

In [306]:
columns[0]

'Year'

In [309]:
mask1 = summer.Year == 2012

In [317]:
summer.loc[1:,columns]

,Year,City,Discipline,Athlete,Country,Gender,Event
1,1896,Athens,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle
2,1896,Athens,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors
3,1896,Athens,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors
4,1896,Athens,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors
5,1896,Athens,Swimming,"CHOROPHAS, Efstathios",GRE,Men,1200M Freestyle
...,...,...,...,...,...,...,...
31160,2012,London,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG
31161,2012,London,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG
31162,2012,London,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG
31163,2012,London,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG


In [322]:
summer.loc[[200,300],['Athlete','Medal']]

KeyError: "None of [Index([200, 300], dtype='object', name='Athlete')] are in the [index]"

In [324]:
summer.set_index('Athlete', inplace = True)

KeyError: "None of ['Athlete'] are in the columns"

In [335]:
summer.loc[['HERSCHMANN, Otto'],['Gender']]

,Gender
Athlete,
"HERSCHMANN, Otto",Men
"HERSCHMANN, Otto",Men
